[project]
name = "chinapopulation"
version = "0.1.0"
description = ""
authors = [{ name = "vicalloy", email = "zbirder@gmail.com" }]
requires-python = ">=3.10"
readme = "README.md"
dependencies = ["plotly>=5.24.0,<6"]

[dependency-groups]
dev = ["pre-commit>=3.8.0,<4"]

[tool.uv]

[[tool.uv.index]]
name = "bfsu"
url = "https://mirrors.bfsu.edu.cn/pypi/web/simple/"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
